import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { AlertCircle, ChevronLeft, ChevronRight, Filter, RotateCcw } from "lucide-react";

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:3001";
const PAGE_SIZE = 20;
const severityOrder: Record<string, number> = { LOW: 1, MEDIUM: 2, HIGH: 3 };
type Conflict = { id: string; politicianName: string; city: string; conflictType: string; severity: string; agendaItemSummary: string; detectedAt: string };
type SortKey = "severity" | "detectedAt";
const title = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase());
const severityClass = (severity: string) => severity.toUpperCase() === "HIGH" ? "bg-red-50 text-red-800 ring-red-200" : severity.toUpperCase() === "MEDIUM" ? "bg-amber-50 text-amber-800 ring-amber-200" : "bg-blue-50 text-blue-800 ring-blue-200";

export function meta() { return [{ title: "Conflict flags | FAIR" }, { name: "description", content: "Browse potential conflicts identified from public Form 700 disclosures and local government agendas." }]; }

export default function ConflictsDashboard() {
  const [conflicts, setConflicts] = useState<Conflict[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [city, setCity] = useState(""); const [type, setType] = useState(""); const [severity, setSeverity] = useState(""); const [sort, setSort] = useState<SortKey>("detectedAt"); const [page, setPage] = useState(1);
  useEffect(() => { const controller = new AbortController(); fetch(`${API_URL}/api/conflicts`, { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error("The conflict list is unavailable right now."); return response.json(); }).then((payload) => setConflicts(Array.isArray(payload.data) ? payload.data : [])).catch((reason) => { if (reason.name !== "AbortError") setError(reason.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const cities = useMemo(() => [...new Set(conflicts.map((item) => item.city).filter(Boolean))].sort(), [conflicts]);
  const types = useMemo(() => [...new Set(conflicts.map((item) => item.conflictType).filter(Boolean))].sort(), [conflicts]);
  const filtered = useMemo(() => conflicts.filter((item) => (!city || item.city === city) && (!type || item.conflictType === type) && (!severity || item.severity.toUpperCase() === severity)).sort((left, right) => sort === "severity" ? (severityOrder[right.severity.toUpperCase()] ?? 0) - (severityOrder[left.severity.toUpperCase()] ?? 0) : new Date(right.detectedAt).getTime() - new Date(left.detectedAt).getTime()), [conflicts, city, type, severity, sort]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const hasFilters = Boolean(city || type || severity);
  function updateFilter(setter: (value: string) => void, value: string) { setter(value); setPage(1); }
  function clearFilters() { setCity(""); setType(""); setSeverity(""); setPage(1); }

  return <main className="page-shell"><header className="max-w-3xl"><p className="eyebrow">Public review</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Conflict flags</h1><p className="mt-4 text-lg leading-8 text-slate-600">Explore potential overlaps between reported financial interests and local government agenda items. A flag supports review; it does not establish a legal conflict.</p></header>
    <section className="surface mt-8 p-5" aria-labelledby="filter-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Filter size={18} className="text-blue-700" /><h2 id="filter-heading" className="font-semibold">Filter records</h2></div>{hasFilters && <button type="button" onClick={clearFilters} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700 hover:text-blue-900"><RotateCcw size={15} /> Clear filters</button>}</div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold text-slate-700">City<select value={city} onChange={(event) => updateFilter(setCity, event.target.value)} className="field mt-2"><option value="">All cities</option>{cities.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Flag type<select value={type} onChange={(event) => updateFilter(setType, event.target.value)} className="field mt-2"><option value="">All flag types</option>{types.map((value) => <option key={value} value={value}>{title(value)}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Severity<select value={severity} onChange={(event) => updateFilter(setSeverity, event.target.value)} className="field mt-2"><option value="">All severities</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label className="text-sm font-semibold text-slate-700">Sort by<select value={sort} onChange={(event) => { setSort(event.target.value as SortKey); setPage(1); }} className="field mt-2"><option value="detectedAt">Most recent</option><option value="severity">Highest severity</option></select></label></div></section>
    {error && <div role="alert" className="surface mt-6 border-red-200 bg-red-50 p-5 text-red-800"><AlertCircle className="mr-2 inline" size={18} />{error}</div>}{loading && <div className="surface mt-6 p-8 text-slate-600" role="status">Loading conflict flags…</div>}
    {!loading && !error && <section className="mt-6" aria-label="Conflict flag results"><div className="mb-4 flex items-center justify-between gap-4"><p className="text-sm text-slate-600"><strong className="text-slate-950">{filtered.length}</strong> record{filtered.length === 1 ? "" : "s"}</p><p className="text-sm text-slate-500">Page {page} of {pageCount}</p></div>{visible.length === 0 ? <div className="surface p-12 text-center"><h2 className="text-lg font-semibold">No records match these filters</h2><p className="mt-2 text-sm text-slate-600">Clear a filter to broaden the results.</p></div> : <div className="space-y-3">{visible.map((conflict) => <Link key={conflict.id} to={`/conflicts/${conflict.id}`} className="surface group grid gap-4 p-5 transition hover:border-blue-300 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${severityClass(conflict.severity)}`}>{conflict.severity}</span><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title(conflict.conflictType)}</span></div><h2 className="mt-3 text-lg font-semibold group-hover:text-blue-800">{conflict.politicianName}</h2><p className="mt-1 text-sm text-slate-500">{conflict.city} · Detected {new Date(conflict.detectedAt).toLocaleDateString()}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{conflict.agendaItemSummary}</p></div><span className="text-sm font-semibold text-blue-700">Review details →</span></Link>)}</div>}
      {pageCount > 1 && <nav aria-label="Results pagination" className="mt-6 flex items-center justify-end gap-2"><button className="button-secondary px-3" disabled={page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ChevronLeft size={17} /> Previous</button><button className="button-secondary px-3" disabled={page === pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))}>Next <ChevronRight size={17} /></button></nav>}</section>}
  </main>;
}